### ISSUE TITLE
Add font-display property for @font-face

### ISSUE THREAD

**Issue by EugeniaFok** [csstree/csstree#171] opened 2021-11-09 20:50 UTC
![image](https://user-images.githubusercontent.com/50756938/141002197-3e029560-3666-4ecd-9c95-f0bac5252873.png)
[MSDN](https://developer.mozilla.org/ru/docs/Web/CSS/@font-face/font-display)

**Comment by carlosjeurissen** [comment] 2022-08-14 17:09
@EugeniaFok Seems this has since been fixed as I don't get such error.

**Comment by lahmatiy** [comment] 2022-08-14 20:09
This issue is about https://csstree.github.io/docs/validator.html
It has its own logic for a validation, in particular it exams at-rule's descriptors as a regular declarations what is wrong and the root of the issue.

**Comment by lahmatiy** [comment] 2022-12-15 00:54
The issue is not related to CSSTree itself but to a tool based on it. I've created an issue in right place (see https://github.com/csstree/docs/issues/14) and left some comments. You can follow updates there. Because of this, I'm closing the issue.

**Closed by lahmatiy** 2022-12-15 00:54 UTC
